bug: fix const correctness
gcc 16, correctly, points out some const correctness bugs in the code:

../../src/rist-common.c: In function ‘parse_url_udp_options’:
../../src/rist-common.c:58:15: error: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   58 |         query = strchr( url, '/' );

../src/udpsocket.c: In function ‘udpsocket_parse_url_parameters’:
../src/udpsocket.c:388:15: error: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  388 |         query = strchr( url, '?' );

Both of these warnings are around the usage of
udpsocket_parse_url_parameters. The function takes a URL and parses it
into a list of type udpsocket_url_param. That function usese strtok to
parse the URL, which modifies the url string and thus cannot be const.
Additionally, it populates the list of type udpsocket_url_param with
pointers back into the url string itself. Becuase of this, callers
need a mutable url and those pointers within the list of
udpsocket_url_param to be valid. So have the two call sites create a
mutable copy of the URL to work on, and free the copy before they
return. This will provide a mutable url for strtok as well as provide
for stable pointers within the paramter list key values.

Signed-off-by: Bill Roberts <bill.roberts@arm.com>